### ISSUE TITLE
support redirects?

### ISSUE THREAD

**Issue by creekorful** [creekorful/go-gallery#20]
when renaming an album support making a redirection

something like this:

```yaml
redirects:
  - from: old-renamed-album
    date: new-album-name
```
